-- 0001_seed_models.sql
-- Seed catalogue for the `models` table (DDL lives in db/schema.sql).
-- Run after schema.sql on a fresh install. Idempotent via ON CONFLICT DO NOTHING.
--
-- Editorial columns:
--   gated            TRUE = HuggingFace approval required (Meta Llama, Gemma 3, etc.)
--   native_quant     What the weight files actually are (bf16 for base repos,
--                    nvfp4 for NVIDIA ModelOpt pre-quantised repos).
--   supported_quants Native quant plus anything we can serve on-the-fly (e.g.
--                    bf16 + fp8 via vLLM at load time).

INSERT INTO models (hf_repo_id, display_name, vendor, family, param_count_b, active_param_count_b, quality_tier, supported_quants, native_quant, ngc_container_tag, gated) VALUES
  ('TinyLlama/TinyLlama-1.1B-Chat-v1.0',                 'TinyLlama-1.1B-Chat-v1.0',                    'tinyllama', 'TinyLlama',    1.1, NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('meta-llama/Llama-3.2-3B-Instruct',                   'Llama-3.2-3B-Instruct',                       'meta',      'LLaMA-3',      3,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('meta-llama/Llama-3.1-8B-Instruct',                   'Llama-3.1-8B-Instruct',                       'meta',      'LLaMA-3',      8,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/meta/llama-3.1-8b-instruct:latest',                 TRUE),
  ('meta-llama/Llama-3.3-70B-Instruct',                  'Llama-3.3-70B-Instruct',                      'meta',      'LLaMA-3',      70,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/meta/llama-3.3-70b-instruct:latest',                TRUE),
  ('Qwen/Qwen2.5-7B-Instruct',                           'Qwen2.5-7B-Instruct',                         'alibaba',   'Qwen',         7,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen2.5-14B-Instruct',                          'Qwen2.5-14B-Instruct',                        'alibaba',   'Qwen',         14,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen2.5-32B-Instruct',                          'Qwen2.5-32B-Instruct',                        'alibaba',   'Qwen',         32,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen2.5-72B-Instruct',                          'Qwen2.5-72B-Instruct',                        'alibaba',   'Qwen',         72,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/QwQ-32B',                                       'QwQ-32B',                                     'alibaba',   'QwQ',          32,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3-8B',                                      'Qwen3-8B',                                    'alibaba',   'Qwen',         8,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3-14B',                                     'Qwen3-14B',                                   'alibaba',   'Qwen',         14,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3-32B',                                     'Qwen3-32B',                                   'alibaba',   'Qwen',         32,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3-30B-A3B',                                 'Qwen3-30B-A3B',                               'alibaba',   'Qwen',         30,  3,    '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3.5-9B',                                    'Qwen3.5-9B',                                  'alibaba',   'Qwen',         9,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3.5-27B',                                   'Qwen3.5-27B',                                 'alibaba',   'Qwen',         27,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('Qwen/Qwen3.5-35B-A3B',                               'Qwen3.5-35B-A3B',                             'alibaba',   'Qwen',         35,  3,    '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',            'DeepSeek-R1-Distill-Qwen-7B',                 'deepseek',  'DeepSeek-R1',  7,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('deepseek-ai/DeepSeek-R1-Distill-Llama-8B',           'DeepSeek-R1-Distill-Llama-8B',                'deepseek',  'DeepSeek-R1',  8,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',           'DeepSeek-R1-Distill-Qwen-14B',                'deepseek',  'DeepSeek-R1',  14,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',           'DeepSeek-R1-Distill-Qwen-32B',                'deepseek',  'DeepSeek-R1',  32,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('deepseek-ai/DeepSeek-R1-Distill-Llama-70B',          'DeepSeek-R1-Distill-Llama-70B',               'deepseek',  'DeepSeek-R1',  70,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('google/gemma-3-4b-it',                               'Gemma-3-4B-IT',                               'google',    'Gemma',        4,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('google/gemma-3-12b-it',                              'Gemma-3-12B-IT',                              'google',    'Gemma',        12,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('google/gemma-3-27b-it',                              'Gemma-3-27B-IT',                              'google',    'Gemma',        27,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            TRUE),
  ('google/gemma-4-31b-it',                              'Gemma-4-31B-IT',                              'google',    'Gemma',        31,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('google/gemma-4-26b-A4B-it',                          'Gemma-4-26B-A4B-IT',                          'google',    'Gemma',        25,  4,    '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('google/gemma-4-e4b-it',                              'Gemma-4-E4B-IT',                              'google',    'Gemma',        4.5, NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('microsoft/Phi-4-mini-instruct',                      'Phi-4-Mini-Instruct',                         'microsoft', 'Phi',          3.8, NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('microsoft/phi-4',                                    'Phi-4',                                       'microsoft', 'Phi',          14,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('mistralai/Mistral-Small-3.1-24B-Instruct-2503',      'Mistral-Small-3.1-24B-Instruct',              'mistral',   'Mistral',      24,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('mistralai/Mistral-Small-3.2-24B-Instruct-2506',      'Mistral-Small-3.2-24B-Instruct',              'mistral',   'Mistral',      24,  NULL, '13b-class', ARRAY['bf16','fp8'], 'bf16',  NULL,                                                            FALSE),
  ('mistralai/Mixtral-8x7B-Instruct-v0.1',               'Mixtral-8x7B-Instruct-v0.1',                  'mistral',   'Mixtral',      46,  13,   '13b-class', ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/mistralai/mixtral-8x7b-instruct-v01:latest',        FALSE),
  ('nvidia/Llama-3.1-8B-Instruct-NVFP4',                 'Llama-3.1-8B-Instruct (NVFP4)',               'nvidia',    'LLaMA-3',      8,   NULL, '7b-class',  ARRAY['nvfp4'],      'nvfp4', NULL,                                                            TRUE),
  ('nvidia/Gemma-4-31B-IT-NVFP4',                        'Gemma-4-31B-IT (NVFP4)',                      'nvidia',    'Gemma',        31,  NULL, '13b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            FALSE),
  ('nvidia/Llama-3.3-70B-Instruct-NVFP4',                'Llama-3.3-70B-Instruct (NVFP4)',              'nvidia',    'LLaMA-3',      70,  NULL, '70b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            TRUE),
  ('nvidia/Llama-4-Scout-17B-16E-Instruct-NVFP4',        'Llama-4-Scout-17B-16E (NVFP4)',               'nvidia',    'LLaMA-4',      109, 17,   '70b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            TRUE),
  ('nvidia/Qwen3-8B-NVFP4',                              'Qwen3-8B (NVFP4)',                            'nvidia',    'Qwen',         8,   NULL, '7b-class',  ARRAY['nvfp4'],      'nvfp4', NULL,                                                            FALSE),
  ('nvidia/Qwen3-14B-NVFP4',                             'Qwen3-14B (NVFP4)',                           'nvidia',    'Qwen',         14,  NULL, '13b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            FALSE),
  ('nvidia/Qwen3-32B-NVFP4',                             'Qwen3-32B (NVFP4)',                           'nvidia',    'Qwen',         32,  NULL, '13b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            FALSE),
  ('nvidia/Qwen3-30B-A3B-NVFP4',                         'Qwen3-30B-A3B (NVFP4)',                       'nvidia',    'Qwen',         30,  3,    '13b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            FALSE),
  ('nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-NVFP4',        'Nemotron-3-Nano-30B-A3B (NVFP4)',             'nvidia',    'Nemotron',     30,  3,    '13b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            TRUE),
  ('nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4',     'Nemotron-3-Super-120B-A12B (NVFP4)',          'nvidia',    'Nemotron',     120, 12,   '70b-class', ARRAY['nvfp4'],      'nvfp4', NULL,                                                            TRUE),
  ('nvidia/Nemotron-Mini-4B-Instruct',                   'Nemotron-Mini-4B-Instruct',                   'nvidia',    'Nemotron',     4,   NULL, '7b-class',  ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/nvidia/nemotron-mini-4b-instruct:latest',           TRUE),
  ('nvidia/Llama-3_3-Nemotron-Super-49B-v1',             'Nemotron-Super-49B-v1',                       'nvidia',    'Nemotron',     49,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/nvidia/nemotron-super-49b-v1:latest',               FALSE),
  ('nvidia/Llama-3.1-Nemotron-70B-Instruct-HF',          'Llama-3.1-Nemotron-70B-Instruct',             'nvidia',    'Nemotron',     70,  NULL, '70b-class', ARRAY['bf16','fp8'], 'bf16',  'nvcr.io/nim/nvidia/llama-3.1-nemotron-70b-instruct:latest',     TRUE)
ON CONFLICT (hf_repo_id) DO NOTHING;
