import type { EnrichedModel, GPU } from './types'

export const SEED_MODELS: EnrichedModel[] = [

  // ─── Testing ──────────────────────────────────────────────────────────────
  {
    hfRepoId: 'TinyLlama/TinyLlama-1.1B-Chat-v1.0',
    displayName: 'TinyLlama-1.1B-Chat-v1.0',
    vendor: 'tinyllama', family: 'TinyLlama', archType: 'dense',
    paramCountB: 1.1, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 2.2, vramFp8Gb: 1.1, vramNvfp4Gb: 0.6,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 1_200_000,
    tags: ['apache2'],
  },

  // ─── Meta LLaMA ───────────────────────────────────────────────────────────
  {
    hfRepoId: 'meta-llama/Llama-3.2-3B-Instruct',
    displayName: 'Llama-3.2-3B-Instruct',
    vendor: 'meta', family: 'LLaMA-3', archType: 'dense',
    paramCountB: 3, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 6, vramFp8Gb: 3, vramNvfp4Gb: 2,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 3_400_000,
    tags: ['gated'],
  },
  {
    hfRepoId: 'meta-llama/Llama-3.1-8B-Instruct',
    displayName: 'Llama-3.1-8B-Instruct',
    vendor: 'meta', family: 'LLaMA-3', archType: 'dense',
    paramCountB: 8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 16, vramFp8Gb: 8, vramNvfp4Gb: 4,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/meta/llama-3.1-8b-instruct:latest',
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 8_900_000,
    tags: ['gated', 'ngc'],
  },
  {
    hfRepoId: 'meta-llama/Llama-3.3-70B-Instruct',
    displayName: 'Llama-3.3-70B-Instruct',
    vendor: 'meta', family: 'LLaMA-3', archType: 'dense',
    paramCountB: 70, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 140, vramFp8Gb: 70, vramNvfp4Gb: 35,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/meta/llama-3.3-70b-instruct:latest',
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 4_800_000,
    tags: ['gated', 'ngc'],
  },

  // ─── Alibaba Qwen 2.5 ─────────────────────────────────────────────────────
  {
    hfRepoId: 'Qwen/Qwen2.5-7B-Instruct',
    displayName: 'Qwen2.5-7B-Instruct',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 7, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 14, vramFp8Gb: 7, vramNvfp4Gb: 4,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 3_100_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen2.5-14B-Instruct',
    displayName: 'Qwen2.5-14B-Instruct',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 14, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 28, vramFp8Gb: 14, vramNvfp4Gb: 7,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_600_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen2.5-32B-Instruct',
    displayName: 'Qwen2.5-32B-Instruct',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 32, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 64, vramFp8Gb: 32, vramNvfp4Gb: 16,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 1_800_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen2.5-72B-Instruct',
    displayName: 'Qwen2.5-72B-Instruct',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 72, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 144, vramFp8Gb: 72, vramNvfp4Gb: 36,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_200_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/QwQ-32B',
    displayName: 'QwQ-32B',
    vendor: 'alibaba', family: 'QwQ', archType: 'dense',
    paramCountB: 32, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 64, vramFp8Gb: 32, vramNvfp4Gb: 16,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_900_000,
    tags: ['apache2'],
  },

  // ─── Alibaba Qwen 3 ───────────────────────────────────────────────────────
  {
    hfRepoId: 'Qwen/Qwen3-8B',
    displayName: 'Qwen3-8B',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 16, vramFp8Gb: 8, vramNvfp4Gb: 4,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 3_200_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen3-14B',
    displayName: 'Qwen3-14B',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 14, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 28, vramFp8Gb: 14, vramNvfp4Gb: 7,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_400_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen3-32B',
    displayName: 'Qwen3-32B',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 32, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 64, vramFp8Gb: 32, vramNvfp4Gb: 16,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 1_900_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen3-30B-A3B',
    displayName: 'Qwen3-30B-A3B',
    vendor: 'alibaba', family: 'Qwen', archType: 'moe',
    paramCountB: 30, activeParamCountB: 3, qualityTier: '13b-class',
    vramFp16Gb: 60, vramFp8Gb: 30, vramNvfp4Gb: 15,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_100_000,
    tags: ['apache2'],
  },

  // ─── Alibaba Qwen 3.5 (multimodal — text inference supported) ────────────
  {
    hfRepoId: 'Qwen/Qwen3.5-9B',
    displayName: 'Qwen3.5-9B',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 9, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 18, vramFp8Gb: 9, vramNvfp4Gb: 5,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 5_550_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen3.5-27B',
    displayName: 'Qwen3.5-27B',
    vendor: 'alibaba', family: 'Qwen', archType: 'dense',
    paramCountB: 27, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 54, vramFp8Gb: 27, vramNvfp4Gb: 14,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 3_140_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'Qwen/Qwen3.5-35B-A3B',
    displayName: 'Qwen3.5-35B-A3B',
    vendor: 'alibaba', family: 'Qwen', archType: 'moe',
    paramCountB: 35, activeParamCountB: 3, qualityTier: '13b-class',
    vramFp16Gb: 70, vramFp8Gb: 35, vramNvfp4Gb: 18,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 3_580_000,
    tags: ['apache2'],
  },

  // ─── DeepSeek ─────────────────────────────────────────────────────────────
  {
    hfRepoId: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
    displayName: 'DeepSeek-R1-Distill-Qwen-7B',
    vendor: 'deepseek', family: 'DeepSeek-R1', archType: 'dense',
    paramCountB: 7, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 14, vramFp8Gb: 7, vramNvfp4Gb: 4,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'mit', mauLimit: null, downloadsMonthly: 2_100_000,
    tags: ['mit'],
  },
  {
    hfRepoId: 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
    displayName: 'DeepSeek-R1-Distill-Llama-8B',
    vendor: 'deepseek', family: 'DeepSeek-R1', archType: 'dense',
    paramCountB: 8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 16, vramFp8Gb: 8, vramNvfp4Gb: 4,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 1_400_000,
    tags: ['gated'],
  },
  {
    hfRepoId: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
    displayName: 'DeepSeek-R1-Distill-Qwen-14B',
    vendor: 'deepseek', family: 'DeepSeek-R1', archType: 'dense',
    paramCountB: 14, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 28, vramFp8Gb: 14, vramNvfp4Gb: 7,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'mit', mauLimit: null, downloadsMonthly: 1_900_000,
    tags: ['mit'],
  },
  {
    hfRepoId: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    displayName: 'DeepSeek-R1-Distill-Qwen-32B',
    vendor: 'deepseek', family: 'DeepSeek-R1', archType: 'dense',
    paramCountB: 32, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 64, vramFp8Gb: 32, vramNvfp4Gb: 16,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'mit', mauLimit: null, downloadsMonthly: 2_400_000,
    tags: ['mit'],
  },
  {
    hfRepoId: 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
    displayName: 'DeepSeek-R1-Distill-Llama-70B',
    vendor: 'deepseek', family: 'DeepSeek-R1', archType: 'dense',
    paramCountB: 70, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 140, vramFp8Gb: 70, vramNvfp4Gb: 35,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 3_200_000,
    tags: ['gated'],
  },
  // ─── Google Gemma 3 ───────────────────────────────────────────────────────
  {
    hfRepoId: 'google/gemma-3-4b-it',
    displayName: 'Gemma-3-4B-IT',
    vendor: 'google', family: 'Gemma', archType: 'dense',
    paramCountB: 4, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 8, vramFp8Gb: 4, vramNvfp4Gb: 2,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'gated', mauLimit: null, downloadsMonthly: 3_000_000,
    tags: ['gated'],
  },
  {
    hfRepoId: 'google/gemma-3-12b-it',
    displayName: 'Gemma-3-12B-IT',
    vendor: 'google', family: 'Gemma', archType: 'dense',
    paramCountB: 12, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 24, vramFp8Gb: 12, vramNvfp4Gb: 6,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'gated', mauLimit: null, downloadsMonthly: 2_500_000,
    tags: ['gated'],
  },
  {
    hfRepoId: 'google/gemma-3-27b-it',
    displayName: 'Gemma-3-27B-IT',
    vendor: 'google', family: 'Gemma', archType: 'dense',
    paramCountB: 27, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 54, vramFp8Gb: 27, vramNvfp4Gb: 14,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'gated', mauLimit: null, downloadsMonthly: 1_800_000,
    tags: ['gated'],
  },

  // ─── Google Gemma 4 ───────────────────────────────────────────────────────
  {
    hfRepoId: 'google/gemma-4-31b-it',
    displayName: 'Gemma-4-31B-IT',
    vendor: 'google', family: 'Gemma', archType: 'dense',
    paramCountB: 31, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 62, vramFp8Gb: 31, vramNvfp4Gb: 16,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_440_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'google/gemma-4-26b-A4B-it',
    displayName: 'Gemma-4-26B-A4B-IT',
    vendor: 'google', family: 'Gemma', archType: 'moe',
    paramCountB: 25, activeParamCountB: 4, qualityTier: '13b-class',
    vramFp16Gb: 50, vramFp8Gb: 25, vramNvfp4Gb: 13,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 1_910_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'google/gemma-4-e4b-it',
    displayName: 'Gemma-4-E4B-IT',
    vendor: 'google', family: 'Gemma', archType: 'dense',
    paramCountB: 4.5, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 9, vramFp8Gb: 4.5, vramNvfp4Gb: 2.5,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 1_390_000,
    tags: ['apache2'],
  },

  // ─── Microsoft Phi ────────────────────────────────────────────────────────
  {
    hfRepoId: 'microsoft/Phi-4-mini-instruct',
    displayName: 'Phi-4-Mini-Instruct',
    vendor: 'microsoft', family: 'Phi', archType: 'dense',
    paramCountB: 3.8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 8, vramFp8Gb: 4, vramNvfp4Gb: 2,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'mit', mauLimit: null, downloadsMonthly: 2_000_000,
    tags: ['mit'],
  },
  {
    hfRepoId: 'microsoft/phi-4',
    displayName: 'Phi-4',
    vendor: 'microsoft', family: 'Phi', archType: 'dense',
    paramCountB: 14, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 28, vramFp8Gb: 14, vramNvfp4Gb: 7,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'mit', mauLimit: null, downloadsMonthly: 2_100_000,
    tags: ['mit'],
  },

  // ─── Mistral ──────────────────────────────────────────────────────────────
  {
    hfRepoId: 'mistralai/Mistral-Small-3.1-24B-Instruct-2503',
    displayName: 'Mistral-Small-3.1-24B-Instruct',
    vendor: 'mistral', family: 'Mistral', archType: 'dense',
    paramCountB: 24, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 48, vramFp8Gb: 24, vramNvfp4Gb: 12,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 980_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'mistralai/Mistral-Small-3.2-24B-Instruct-2506',
    displayName: 'Mistral-Small-3.2-24B-Instruct',
    vendor: 'mistral', family: 'Mistral', archType: 'dense',
    paramCountB: 24, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 48, vramFp8Gb: 24, vramNvfp4Gb: 12,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 720_000,
    tags: ['apache2'],
  },
  {
    hfRepoId: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    displayName: 'Mixtral-8x7B-Instruct-v0.1',
    vendor: 'mistral', family: 'Mixtral', archType: 'moe',
    paramCountB: 46, activeParamCountB: 13, qualityTier: '13b-class',
    vramFp16Gb: 92, vramFp8Gb: 46, vramNvfp4Gb: 23,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/mistralai/mixtral-8x7b-instruct-v01:latest',
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 2_600_000,
    tags: ['apache2', 'ngc'],
  },

  // ─── NVFP4 Pre-quantized (TRT-LLM · RTX Pro 6000 only) ───────────────────
  // Separate HF repos under nvidia/ — weights pre-quantized with ModelOpt.
  // TRT-LLM still compiles an engine from these, but skips calibration (~30 min vs hours).
  {
    hfRepoId: 'nvidia/Llama-3.1-8B-Instruct-NVFP4',
    displayName: 'Llama-3.1-8B-Instruct (NVFP4)',
    vendor: 'nvidia', family: 'LLaMA-3', archType: 'dense',
    paramCountB: 8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 16, vramFp8Gb: 8, vramNvfp4Gb: 4,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 112_000,
    tags: ['nvidia', 'nvfp4', 'gated'],
  },
  {
    hfRepoId: 'nvidia/Gemma-4-31B-IT-NVFP4',
    displayName: 'Gemma-4-31B-IT (NVFP4)',
    vendor: 'nvidia', family: 'Gemma', archType: 'dense',
    paramCountB: 31, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 62, vramFp8Gb: 31, vramNvfp4Gb: 16,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 757_000,
    tags: ['nvidia', 'nvfp4', 'apache2'],
  },
  {
    hfRepoId: 'nvidia/Llama-3.3-70B-Instruct-NVFP4',
    displayName: 'Llama-3.3-70B-Instruct (NVFP4)',
    vendor: 'nvidia', family: 'LLaMA-3', archType: 'dense',
    paramCountB: 70, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 140, vramFp8Gb: 70, vramNvfp4Gb: 35,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 136_000,
    tags: ['nvidia', 'nvfp4', 'gated'],
  },
  {
    hfRepoId: 'nvidia/Llama-4-Scout-17B-16E-Instruct-NVFP4',
    displayName: 'Llama-4-Scout-17B-16E (NVFP4)',
    vendor: 'nvidia', family: 'LLaMA-4', archType: 'moe',
    paramCountB: 109, activeParamCountB: 17, qualityTier: '70b-class',
    vramFp16Gb: 218, vramFp8Gb: 109, vramNvfp4Gb: 55,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 65_000,
    tags: ['nvidia', 'nvfp4', 'gated'],
  },
  {
    hfRepoId: 'nvidia/Qwen3-8B-NVFP4',
    displayName: 'Qwen3-8B (NVFP4)',
    vendor: 'nvidia', family: 'Qwen', archType: 'dense',
    paramCountB: 8, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 16, vramFp8Gb: 8, vramNvfp4Gb: 4,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 30_000,
    tags: ['nvidia', 'nvfp4', 'apache2'],
  },
  {
    hfRepoId: 'nvidia/Qwen3-14B-NVFP4',
    displayName: 'Qwen3-14B (NVFP4)',
    vendor: 'nvidia', family: 'Qwen', archType: 'dense',
    paramCountB: 14, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 28, vramFp8Gb: 14, vramNvfp4Gb: 7,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 147_000,
    tags: ['nvidia', 'nvfp4', 'apache2'],
  },
  {
    hfRepoId: 'nvidia/Qwen3-32B-NVFP4',
    displayName: 'Qwen3-32B (NVFP4)',
    vendor: 'nvidia', family: 'Qwen', archType: 'dense',
    paramCountB: 32, activeParamCountB: null, qualityTier: '13b-class',
    vramFp16Gb: 64, vramFp8Gb: 32, vramNvfp4Gb: 16,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 91_000,
    tags: ['nvidia', 'nvfp4', 'apache2'],
  },
  {
    hfRepoId: 'nvidia/Qwen3-30B-A3B-NVFP4',
    displayName: 'Qwen3-30B-A3B (NVFP4)',
    vendor: 'nvidia', family: 'Qwen', archType: 'moe',
    paramCountB: 30, activeParamCountB: 3, qualityTier: '13b-class',
    vramFp16Gb: 60, vramFp8Gb: 30, vramNvfp4Gb: 15,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'apache2', mauLimit: null, downloadsMonthly: 266_000,
    tags: ['nvidia', 'nvfp4', 'apache2'],
  },
  {
    hfRepoId: 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-NVFP4',
    displayName: 'Nemotron-3-Nano-30B-A3B (NVFP4)',
    vendor: 'nvidia', family: 'Nemotron', archType: 'moe',
    paramCountB: 30, activeParamCountB: 3, qualityTier: '13b-class',
    vramFp16Gb: 60, vramFp8Gb: 30, vramNvfp4Gb: 15,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 612_000,
    tags: ['nvidia', 'nvfp4'],
  },
  {
    hfRepoId: 'nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4',
    displayName: 'Nemotron-3-Super-120B-A12B (NVFP4)',
    vendor: 'nvidia', family: 'Nemotron', archType: 'moe',
    paramCountB: 120, activeParamCountB: 12, qualityTier: '70b-class',
    vramFp16Gb: 240, vramFp8Gb: 120, vramNvfp4Gb: 60,
    supportedQuants: ['nvfp4'],
    ngcContainerTag: null,
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 1_660_000,
    tags: ['nvidia', 'nvfp4'],
  },

  // ─── NVIDIA Nemotron (TRT-LLM / NIM — best with TRT-LLM engine) ──────────
  {
    hfRepoId: 'nvidia/Nemotron-Mini-4B-Instruct',
    displayName: 'Nemotron-Mini-4B-Instruct',
    vendor: 'nvidia', family: 'Nemotron', archType: 'dense',
    paramCountB: 4, activeParamCountB: null, qualityTier: '7b-class',
    vramFp16Gb: 8, vramFp8Gb: 4, vramNvfp4Gb: 2,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/nvidia/nemotron-mini-4b-instruct:latest',
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 310_000,
    tags: ['nvidia', 'ngc'],
  },
  {
    hfRepoId: 'nvidia/Llama-3_3-Nemotron-Super-49B-v1',
    displayName: 'Nemotron-Super-49B-v1',
    vendor: 'nvidia', family: 'Nemotron', archType: 'dense',
    paramCountB: 49, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 98, vramFp8Gb: 49, vramNvfp4Gb: 25,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/nvidia/nemotron-super-49b-v1:latest',
    licenceType: 'other', mauLimit: null, downloadsMonthly: 620_000,
    tags: ['nvidia', 'ngc'],
  },
  {
    hfRepoId: 'nvidia/Llama-3.1-Nemotron-70B-Instruct',
    displayName: 'Llama-3.1-Nemotron-70B-Instruct',
    vendor: 'nvidia', family: 'Nemotron', archType: 'dense',
    paramCountB: 70, activeParamCountB: null, qualityTier: '70b-class',
    vramFp16Gb: 140, vramFp8Gb: 70, vramNvfp4Gb: 35,
    supportedQuants: ['bf16', 'fp8'],
    ngcContainerTag: 'nvcr.io/nim/nvidia/llama-3.1-nemotron-70b-instruct:latest',
    licenceType: 'llama3', mauLimit: 700_000_000, downloadsMonthly: 2_400_000,
    tags: ['nvidia', 'ngc'],
  },
]

export const SEED_GPUS: GPU[] = [
  {
    id: 'rtx-pro-6000',
    name: 'RTX Pro 6000',
    optionLabel: 'Option B',
    vramGb: 96,
    bf16Tflops: 314.6,
    tensorCoreCaps: ['fp16', 'fp4', 'int8'],
    trtLlmSupported: true,
    vllmSupported: true,
    targetWorkload: 'Large models (up to 70B FP16), NVFP4 capable',
  },
  {
    id: 'rtx-4000-ada',
    name: 'RTX 4000 Ada',
    optionLabel: 'Option A',
    vramGb: 20,
    bf16Tflops: 48.7,
    tensorCoreCaps: ['fp16', 'int8'],
    trtLlmSupported: true,
    vllmSupported: true,
    targetWorkload: 'Smaller models (≤13B FP16), cost-efficient tier',
  },
]
